[project]
name = "nsphere"
description = "Convert between cartesian and hyperspherical coordinates"
version = "0.0.1"
requires-python = ">=3.9"
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
dependencies = ["numpy"]

[project.optional-dependencies]
dev = ["black", "isort", "pip-tools", "pytest"]

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=42"]

[tool.black]
line-length = 120
target-version = ["py39"]
preview = true
